import "./globals.css";
import { Nunito } from "next/font/google";
import Script from "next/script";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Risk-Viz",
  description: "Generated by create next app",
  icons: {
    icon: "/next.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
